### ISSUE TITLE
Settings - Phone number issue when more than one phone number is listed

### ISSUE THREAD

**Issue by kevino71** [michaelkourlas/voipms-sms#1]
In the Settings screen, I click on the phone icon to select my voip.ms phone number. On the pop-up form are my two voip.ms phone numbers. I would like to select the second number, but the first one is selected by default and when I click on the second phone number, the first one stays selected.
I cannot select just the second number.
The first number is what returns back the Settings form.
Using a Galaxy Nexus phone with Android 4.3

**Comment by michaelkourlas** [comment]
I'm aware of this issue, and I'm working on a fix. Unfortunately, I'm a student, so my time is limited. It'll be released as soon as possible.

**Comment by michaelkourlas** [comment]
I've rewritten the application for native Android, so this issue shouldn't exist any longer. If it does, please open a new issue.
