### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by Niveous73** [michaelkourlas/voipms-sms#2]
I can setup and select the phone number. But when i go back it says 

Error decoding VOIP.ms API Response. Are username, password, and selected phone number correct?

I think username is the email addy i login to voip.ms 
I have enabled API and set the password
Also set ip to 0.0.0.0

I thought what issue could be.

**Comment by michaelkourlas** [comment]
I've rewritten the application for native Android, so this issue shouldn't exist any longer. If it does, please open a new issue.
